// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    history: {
        name: "history";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          search_id: string;
          /** @sqlType STRING */
          business_type: string;
          /** @sqlType STRING */
          location: string;
          /** @sqlType BIGINT */
          businesses: number;
          /** @sqlType DOUBLE */
          avg_rating: number;
          /** @sqlType STRING */
          search_time: string;
        }>;
      };
    kpis: {
        name: "kpis";
        parameters: {
          /** STRING - use sql.string() */
          search_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          total_businesses: number;
          /** @sqlType DOUBLE */
          avg_rating: number;
          /** @sqlType INT */
          avg_reviews: number;
        }>;
      };
    leaderboard: {
        name: "leaderboard";
        parameters: {
          /** STRING - use sql.string() */
          search_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          name: string;
          /** @sqlType DOUBLE */
          rating: number;
          /** @sqlType INT */
          review_count: number;
          /** @sqlType STRING */
          price_level: string;
          /** @sqlType STRING */
          address: string;
          /** @sqlType STRING */
          category: string;
          /** @sqlType STRING */
          place_url: string;
          /** @sqlType STRING */
          search_title: string;
        }>;
      };
    ratings_dist: {
        name: "ratings_dist";
        parameters: {
          /** STRING - use sql.string() */
          search_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          rating_bucket: string;
          /** @sqlType BIGINT */
          businesses: number;
        }>;
      };
  }
}
