"""Action layer: turn violations into enforcement artifacts.

Primary (with Google creds): a Google Sheets enforcement tracker (worklist, one row
per violation) + one Google Doc notice per violation in a Drive folder.
Fallback (no creds): local notices/*.md + data/enforcement_tracker.csv — so the demo
and cookbook run with zero Google setup.

Trust policy: violations whose price claim is `low` confidence are written to the
tracker flagged "verify manually" but EXCLUDED from auto-generated notices
(a wrong "you're violating MAP" notice is worse than a missed one).
"""
import csv
import hashlib
import json
import re

import config as C

TRACKER_COLS = [
    "sku_id", "brand", "product_name", "size", "seller_name", "seller_domain", "seller_type",
    "advertised_price_num", "map_price", "gap_abs", "gap_pct", "price_confidence",
    "status", "listing_url", "evidence_url", "observed_at",
]


def _slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (s or "").lower()).strip("-")[:60]


def notice_title(v: dict) -> str:
    return f"MAP Violation Notice — {v['brand']} {v['product_name']} ({v['size']}) — {v['seller_domain']}"


def notice_plaintext(v: dict) -> str:
    """Clean plain-text notice for Google Docs (markdown syntax would render literally)."""
    return "\n".join([
        notice_title(v), "",
        f"Date observed: {v.get('observed_at') or 'n/a'}",
        f"Seller: {v.get('seller_name') or v['seller_domain']} ({v['seller_domain']}) — {v.get('seller_type','unknown')}",
        f"Listing: {v['listing_url']}", "",
        "VIOLATION",
        f"Advertised price: ${v['advertised_price_num']:.2f}",
        f"Your MAP: ${v['map_price']:.2f}",
        f"Gap: ${v['gap_abs']:.2f} ({v['gap_pct']}% below MAP)", "",
        "CITED EVIDENCE",
        v.get("evidence_excerpt") or "(price observed on listing page)",
        f"Source: {v.get('evidence_url') or v['listing_url']}",
        f"Price-claim confidence: {v.get('price_confidence') or 'n/a'}", "",
        "— Generated by MAP Compliance Monitor. The advertised price above was observed on "
        "the cited listing and is below the product's Minimum Advertised Price.",
    ]) + "\n"


def doc_requests(v: dict) -> list:
    """Google Docs batchUpdate requests: insert plain text, then bold+heading the title line."""
    text = notice_plaintext(v)
    title_len = len(notice_title(v))
    return [
        {"insertText": {"location": {"index": 1}, "text": text}},
        {"updateParagraphStyle": {
            "range": {"startIndex": 1, "endIndex": 1 + title_len},
            "paragraphStyle": {"namedStyleType": "HEADING_1"}, "fields": "namedStyleType"}},
        {"updateTextStyle": {
            "range": {"startIndex": 1, "endIndex": 1 + title_len},
            "textStyle": {"bold": True}, "fields": "bold"}},
    ]


def notice_markdown(v: dict) -> str:
    return f"""# {notice_title(v)}

**Date observed:** {v.get('observed_at') or 'n/a'}
**Seller:** {v.get('seller_name') or v['seller_domain']} ({v['seller_domain']}) — _{v.get('seller_type','unknown')}_
**Listing:** {v['listing_url']}

## Violation
| Advertised price | Your MAP | Gap |
|---|---|---|
| ${v['advertised_price_num']:.2f} | ${v['map_price']:.2f} | ${v['gap_abs']:.2f} ({v['gap_pct']}% below MAP) |

## Cited evidence
> {v.get('evidence_excerpt') or '(price observed on listing page)'}

Source: {v.get('evidence_url') or v['listing_url']}
Price-claim confidence: {v.get('price_confidence') or 'n/a'}

---
_This notice was generated by MAP Compliance Monitor. The advertised price above was
observed on the cited listing and is below the product's Minimum Advertised Price._
"""


def _partition(violations: list[dict]):
    """Return (auto_notice, verify_manually) split by confidence.

    auto = notices to generate, capped to the NOTICE_LIMIT most severe (by gap %);
    the tracker still records every violation.
    """
    manual = [v for v in violations if (v.get("price_confidence") or "").lower() == "low"]
    auto_all = [v for v in violations if (v.get("price_confidence") or "").lower() != "low"]
    auto = sorted(auto_all, key=lambda v: v.get("gap_pct", 0), reverse=True)[: C.NOTICE_LIMIT]
    return auto, manual


def _row_status(v, auto, manual) -> str:
    if v in manual:
        return "verify manually"
    if v in auto:
        return "notice generated"
    return "logged"


def write_local(violations: list[dict]) -> dict:
    auto, manual = _partition(violations)
    # tracker (all violations; low-confidence flagged, below-cap logged)
    rows = []
    for v in violations:
        status = _row_status(v, auto, manual)
        rows.append({**{k: v.get(k) for k in TRACKER_COLS if k != "status"}, "status": status})
    tracker = C.DATA / "enforcement_tracker.csv"
    with open(tracker, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=TRACKER_COLS)
        w.writeheader()
        w.writerows(rows)
    # notices (auto only) — filename unique per violation (domain+SKU can repeat across listings)
    for v in auto:
        disc = hashlib.sha1((v.get("listing_url") or "").encode()).hexdigest()[:6]
        fn = C.NOTICES / f"{v['sku_id']}__{_slug(v['seller_domain'])}__{disc}.md"
        fn.write_text(notice_markdown(v))
    return {"tracker": str(tracker), "total_violations": len(violations),
            "notices_written": len(auto), "flagged_verify": len(manual)}


def _google_services():
    """Return (sheets, docs, drive) services or None if creds unavailable."""
    if not (C.GOOGLE_SA_JSON and C.GOOGLE_SHEET_ID):
        return None
    try:
        from google.oauth2.service_account import Credentials
        from googleapiclient.discovery import build
    except ImportError:
        print("google client libs not installed — using local fallback")
        return None
    scopes = ["https://www.googleapis.com/auth/spreadsheets",
              "https://www.googleapis.com/auth/documents",
              "https://www.googleapis.com/auth/drive"]
    creds = Credentials.from_service_account_file(C.GOOGLE_SA_JSON, scopes=scopes)
    return (build("sheets", "v4", credentials=creds),
            build("docs", "v1", credentials=creds),
            build("drive", "v3", credentials=creds))


def push_google(violations: list[dict]) -> dict:
    svc = _google_services()
    if svc is None:
        print("No Google creds — writing local fallback instead.")
        return {"mode": "local", **write_local(violations)}
    sheets, docs, drive = svc
    auto, manual = _partition(violations)
    # 1) tracker rows
    header = [TRACKER_COLS]
    body = []
    for v in violations:
        row = {**{k: v.get(k) for k in TRACKER_COLS if k != "status"}, "status": _row_status(v, auto, manual)}
        body.append([str(row.get(k, "")) for k in TRACKER_COLS])   # aligned to all 16 columns
    sheets.spreadsheets().values().update(
        spreadsheetId=C.GOOGLE_SHEET_ID, range="A1",
        valueInputOption="RAW", body={"values": header + body}).execute()
    # 2) one Doc per auto violation, in the Drive folder. Degrade gracefully: the Sheet
    #    tracker (above) is the primary artifact; Doc creation can fail on the service
    #    account's zero My-Drive quota (needs a Shared Drive folder).
    created, doc_error = 0, None
    for v in auto:
        meta = {"name": f"{notice_title(v)} — ${v['advertised_price_num']:.2f}",
                "mimeType": "application/vnd.google-apps.document"}
        if C.GOOGLE_DRIVE_FOLDER_ID:
            meta["parents"] = [C.GOOGLE_DRIVE_FOLDER_ID]
        try:
            doc = drive.files().create(body=meta, fields="id", supportsAllDrives=True).execute()
            docs.documents().batchUpdate(documentId=doc["id"], body={"requests": doc_requests(v)}).execute()
            created += 1
        except Exception as e:  # noqa: BLE001
            doc_error = str(e)
            break   # quota/permission errors won't recover mid-loop
    out = {"mode": "google", "total_violations": len(violations), "tracker_rows": len(body),
           "docs_created": created, "notice_cap": C.NOTICE_LIMIT, "flagged_verify": len(manual)}
    if doc_error:
        hint = ("Doc notices need a SHARED DRIVE folder — a service account has no personal "
                "Drive storage. The Sheet tracker was written; set GOOGLE_DRIVE_FOLDER_ID to a "
                "Shared Drive folder for Docs.") if "storageQuota" in doc_error else doc_error
        out["docs_skipped"] = hint
    return out


def main():
    violations = json.loads((C.DATA / "violations.json").read_text())
    if not violations:
        print("no violations to act on")
        return
    result = push_google(violations) if (C.GOOGLE_SA_JSON and C.GOOGLE_SHEET_ID) else {"mode": "local", **write_local(violations)}
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
